config/routes.rb
Rails.application.routes.draw do

root 'static_pages#home'

resources :corsairs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/corsair.rb
class Corsair < ApplicationRecord
  validates :first_name, presence: true,
            length: { maximum: 20 }
 validates :age, presence: true
            validates_inclusion_of :age, in: 15..120
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/corsairs_controller.rb
class CorsairsController < ApplicationController
  def new
    @corsairs = Corsair.new
  end

  def create
corsaire = Corsair.create(post_params)
end

  def show
    @corsairs = Corsair.find(params[:id])
  end

  def edit
    @corsairs = Corsair.find(params[:id])
  end

def update
  @corsairs = Corsair.find(params[:id])
  @corsairs.update(post_params)
  redirect_to corsair_path

end

  def destroy
    @corsairs = Corsair.find(params[:id])
    @corsairs.destroy
    redirect_to corsairs_path

  end

  def index
    @corsairs = Corsair.all
  end

private

  def post_params
  params.require(:corsair).permit(:first_name, :age, :slack_handle, :github_handle, :bio)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/corsairs_helper.rb
module CorsairsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/corsairs/delete.html.erb
<h1>Corsair#delete</h1>
<p>Find me in app/views/corsair/delete.html.erb</p>

app/views/corsairs/edit.html.erb
<h1>Editer le corsaire</h1>


<%= form_for @corsairs do |f| %>
<div class="form_group">
  <p><label>Nom</label>
<%= f.text_field :first_name, class: 'form-control' %></p>
<p><label>Age</label>
<%= f.text_field :age, class: 'form-control' %></p>
<p><label>Pseudo Slack</label>
<%= f.text_field :slack_handle, class: 'form-control' %></p>
<p><label>Pseudo Github</label>
<%= f.text_field :github_handle, class: 'form-control' %></p>
<p><label>Bio</label>
<%= f.text_field :bio, class: 'form-control' %></p>

</div>
<div class="form_group">
  <p><button type="submit" class="btn btn-primary">Modifer le corsaire</button>
</p>
  <p>
    <a href="<%= corsair_path(@corsairs.id) %>" class= "btn btn-danger" data-confirm "êtes vous sur?" data-method = "DELETE">Supprimer le corsaire</a>
  </p>
</div>

<% end %>

app/views/corsairs/index.html.erb
<h1>Corsaires</h1>

<ul id="lol">

  <% @corsairs.each do |corsaire| %>

    <li>

      <%= link_to corsaire.first_name, corsair_path(corsaire) %>
      <%= corsaire.age %>

    </li>

  <% end %>

</ul>



<%= link_to "créer un corsaire", new_corsair_path %>

app/views/corsairs/new.html.erb
<%= form_for(@corsairs) do |f| %>
 <ul>
 <% @corsairs.errors.full_messages.each do |error| %>
   <li><%= error %></li>
 <% end %>
 </ul>
 <p>
   <%= f.label :Nom %><br />
   <%= f.text_field :first_name, class: 'form-control' %>
 </p>
 <p>
   <%= f.label :Age %><br />
   <%= f.text_area :age, class: 'form-control' %>
 </p>

 <p><label>Pseudo Slack</label>
 <%= f.text_field :slack_handle, class: 'form-control' %></p>
 <p><label>Pseudo Github</label>
 <%= f.text_field :github_handle, class: 'form-control' %></p>

 <button type="submit" class="btn btn-primary">Valider le corsaire</button>
<% end %>

app/views/corsairs/show.html.erb
<h1><%= @corsairs.first_name %></h1>
<p> <%= @corsairs.age %> </p>
<% if @corsairs.slack_handle != nil %>
	<p>Voici le pseudo Slack de <%=@corsairs.first_name%> : <%=@corsairs.slack_handle%></p>
<% else %>
	<p><%=@corsairs.first_name%> n'a pas encore renseigné son pseudo Slack !</p>
<% end %>
<p> <%= @corsairs.github_handle %> </p>
<p> <%= @corsairs.bio %> </p>

<p>   <a href="<%= edit_corsair_path %>" class= "btn btn-primary">Editer le corsaire</a>
<p>
  <a href="<%= corsairs_path %>" class= "btn btn-primary">Revenir aux corsaires</a>
</p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Accueil",   '#' %></li>
        <li><%= link_to "Index des corsaires",   '#' %></li>
        <li><%= link_to "Nouveau corsaire", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThpCorsaires</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Bienvenue !</h1>
  <h3>
    Ici, tu peux retrouver les corsaires 🎓
  </h3>
  <%= link_to "Enregistre-toi !", '#', class: "btn btn-lg btn-primary" %>
</div>